package org.springframework.dwarf.card;

public enum StrategyName {
	// Mountain cards
	SEAM,FORGES_ALLOY,GET_HELP,ORC_RAIDERS,DRAGONS_KNOCKERS,SHIDE,
	// Special cards
	MUSTER_AN_ARMY,HOLD_A_COUNCIL,SELL_AN_ITEM,PAST_GLORIES,SPECIAL_ORDER,TURN_BACK,APPRENTICE,COLLAPSE_THE_SHAFTS,RUN_AMOK
}
